[package]
name = "nikolapesevic/pluginiris"
version = "1.0.2"
license = "MIT"
description = "Wrapper for SirMallard/Iris to make plugin development more convenient."
authors = ["Johnny"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["rokit.toml", "example/", "example.project.json", ".vscode/"]

[dependencies]
Iris = "sirmallard/iris@^2.5.0"
Bin = "red-blox/bin@^1.0.0"
Signal = "stravant/goodsignal@0.3.0"