[package]
name = "nikolapesevic/pluginiris"
version = "1.3.2"

license = "MIT"
description = "Wrapper for SirMallard/Iris to make plugin development more convenient."
authors = ["Johnny"]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["default.project.json", "lib", "lib/**", "LICENSE", "wally.toml"]

[dependencies]
Bin = "red-blox/bin@^1.0.0"
Signal = "stravant/goodsignal@0.3.0"