[package]
name = "nikolapesevic/pluginiris"
version = "1.0.0"
description = "Super simple layer built on top of Iris to provide a more convenient interface for using Iris for Studio plugins."
authors = ["Johnny"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Iris = "sirmallard/iris@^2.5.0"
Bin = "red-blox/bin@^1.0.0"
Signal = "red-blox/signal@^1.0.0"